services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dustbid
    ports:
      - "3306:3310"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:bullseye
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always
