services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dustbin
    ports:
      - "3310:3306"

  redis:
    image: redis:bullseye
    ports:
      - "6379:6379"
